//
//  Boards.swift
//  RicochetRobotsPlus
//
//  Created by Leonardo Armelin on 18/04/23.
//

struct Boards {
    static let boardOne: [Tile] = [
        EmptyTile(position: .init(x: 0, y: 0)),
        PartialWall(position: .init(x: 1, y: 0), sidesBlock: [.right]),
        EmptyTile(position: .init(x: 2, y: 0)),
        EmptyTile(position: .init(x: 3, y: 0)),
        EmptyTile(position: .init(x: 4, y: 0)),
        EmptyTile(position: .init(x: 5, y: 0)),
        EmptyTile(position: .init(x: 6, y: 0)),
        EmptyTile(position: .init(x: 7, y: 0)),
        PartialWall(position: .init(x: 8, y: 0), sidesBlock: [.right]),
        EmptyTile(position: .init(x: 9, y: 0)),
        EmptyTile(position: .init(x: 10, y: 0)),
        EmptyTile(position: .init(x: 11, y: 0)),
        EmptyTile(position: .init(x: 12, y: 0)),
        EmptyTile(position: .init(x: 13, y: 0)),
        EmptyTile(position: .init(x: 14, y: 0)),
        EmptyTile(position: .init(x: 15, y: 0)),
        
        EmptyTile(position: .init(x: 0, y: 1)),
        EmptyTile(position: .init(x: 1, y: 1)),
        EmptyTile(position: .init(x: 2, y: 1)),
        EmptyTile(position: .init(x: 3, y: 1)),
        EmptyTile(position: .init(x: 4, y: 1)),
        EmptyTile(position: .init(x: 5, y: 1)),
        EmptyTile(position: .init(x: 6, y: 1)),
        EmptyTile(position: .init(x: 7, y: 1)),
        EmptyTile(position: .init(x: 8, y: 1)),
        EmptyTile(position: .init(x: 9, y: 1)),
        EmptyTile(position: .init(x: 10, y: 1)),
        EmptyTile(position: .init(x: 11, y: 1)),
        EmptyTile(position: .init(x: 12, y: 1)),
        EmptyTile(position: .init(x: 13, y: 1)),
        EmptyTile(position: .init(x: 14, y: 1)),
        EmptyTile(position: .init(x: 15, y: 1)),
        
        EmptyTile(position: .init(x: 0, y: 2)),
        EmptyTile(position: .init(x: 1, y: 2)),
        EmptyTile(position: .init(x: 2, y: 2)),
        EmptyTile(position: .init(x: 3, y: 2)),
        PartialWall(position: .init(x: 4, y: 2), sidesBlock: [.top, .left]),
        EmptyTile(position: .init(x: 5, y: 2)),
        EmptyTile(position: .init(x: 6, y: 2)),
        EmptyTile(position: .init(x: 7, y: 2)),
        EmptyTile(position: .init(x: 8, y: 2)),
        EmptyTile(position: .init(x: 9, y: 2)),
        EmptyTile(position: .init(x: 10, y: 2)),
        EmptyTile(position: .init(x: 11, y: 2)),
        EmptyTile(position: .init(x: 12, y: 2)),
        PartialWall(position: .init(x: 13, y: 2), sidesBlock: [.top, .left]),
        EmptyTile(position: .init(x: 14, y: 2)),
        PartialWall(position: .init(x: 15, y: 2), sidesBlock: [.bottom]),
        
        PartialWall(position: .init(x: 0, y: 3), sidesBlock: [.bottom]),
        PartialWall(position: .init(x: 1, y: 3), sidesBlock: [.top, .right]),
        EmptyTile(position: .init(x: 2, y: 3)),
        EmptyTile(position: .init(x: 3, y: 3)),
        EmptyTile(position: .init(x: 4, y: 3)),
        EmptyTile(position: .init(x: 5, y: 3)),
        EmptyTile(position: .init(x: 6, y: 3)),
        EmptyTile(position: .init(x: 7, y: 3)),
        EmptyTile(position: .init(x: 8, y: 3)),
        EmptyTile(position: .init(x: 9, y: 3)),
        EmptyTile(position: .init(x: 10, y: 3)),
        EmptyTile(position: .init(x: 11, y: 3)),
        EmptyTile(position: .init(x: 12, y: 3)),
        EmptyTile(position: .init(x: 13, y: 3)),
        EmptyTile(position: .init(x: 14, y: 3)),
        EmptyTile(position: .init(x: 15, y: 3)),
        
        EmptyTile(position: .init(x: 0, y: 4)),
        EmptyTile(position: .init(x: 1, y: 4)),
        EmptyTile(position: .init(x: 2, y: 4)),
        EmptyTile(position: .init(x: 3, y: 4)),
        PartialWall(position: .init(x: 4, y: 4), sidesBlock: [.bottom, .left]),
        EmptyTile(position: .init(x: 5, y: 4)),
        EmptyTile(position: .init(x: 6, y: 4)),
        EmptyTile(position: .init(x: 7, y: 4)),
        EmptyTile(position: .init(x: 8, y: 4)),
        EmptyTile(position: .init(x: 9, y: 4)),
        EmptyTile(position: .init(x: 10, y: 4)),
        PartialWall(position: .init(x: 11, y: 4), sidesBlock: [.bottom, .left]),
        EmptyTile(position: .init(x: 12, y: 4)),
        EmptyTile(position: .init(x: 13, y: 4)),
        EmptyTile(position: .init(x: 14, y: 4)),
        EmptyTile(position: .init(x: 15, y: 4)),
        
        EmptyTile(position: .init(x: 0, y: 5)),
        EmptyTile(position: .init(x: 1, y: 5)),
        EmptyTile(position: .init(x: 2, y: 5)),
        EmptyTile(position: .init(x: 3, y: 5)),
        EmptyTile(position: .init(x: 4, y: 5)),
        EmptyTile(position: .init(x: 5, y: 5)),
        EmptyTile(position: .init(x: 6, y: 5)),
        EmptyTile(position: .init(x: 7, y: 5)),
        EmptyTile(position: .init(x: 8, y: 5)),
        EmptyTile(position: .init(x: 9, y: 5)),
        EmptyTile(position: .init(x: 10, y: 5)),
        EmptyTile(position: .init(x: 11, y: 5)),
        EmptyTile(position: .init(x: 12, y: 5)),
        PartialWall(position: .init(x: 13, y: 5), sidesBlock: [.top, .right]),
        EmptyTile(position: .init(x: 14, y: 5)),
        EmptyTile(position: .init(x: 15, y: 5)),
        
        EmptyTile(position: .init(x: 0, y: 6)),
        PartialWall(position: .init(x: 1, y: 6), sidesBlock: [.bottom, .right]),
        EmptyTile(position: .init(x: 2, y: 6)),
        EmptyTile(position: .init(x: 3, y: 6)),
        EmptyTile(position: .init(x: 4, y: 6)),
        EmptyTile(position: .init(x: 5, y: 6)),
        EmptyTile(position: .init(x: 6, y: 6)),
        EmptyTile(position: .init(x: 7, y: 6)),
        EmptyTile(position: .init(x: 8, y: 6)),
        EmptyTile(position: .init(x: 9, y: 6)),
        EmptyTile(position: .init(x: 10, y: 6)),
        EmptyTile(position: .init(x: 11, y: 6)),
        EmptyTile(position: .init(x: 12, y: 6)),
        EmptyTile(position: .init(x: 13, y: 6)),
        PartialWall(position: .init(x: 14, y: 6), sidesBlock: [.bottom, .right]),
        EmptyTile(position: .init(x: 15, y: 6)),
        
        EmptyTile(position: .init(x: 0, y: 7)),
        EmptyTile(position: .init(x: 1, y: 7)),
        EmptyTile(position: .init(x: 2, y: 7)),
        EmptyTile(position: .init(x: 3, y: 7)),
        EmptyTile(position: .init(x: 4, y: 7)),
        EmptyTile(position: .init(x: 5, y: 7)),
        EmptyTile(position: .init(x: 6, y: 7)),
        Wall(position: .init(x: 7, y: 7)),
        Wall(position: .init(x: 8, y: 7)),
        EmptyTile(position: .init(x: 9, y: 7)),
        EmptyTile(position: .init(x: 10, y: 7)),
        EmptyTile(position: .init(x: 11, y: 7)),
        EmptyTile(position: .init(x: 12, y: 7)),
        EmptyTile(position: .init(x: 13, y: 7)),
        EmptyTile(position: .init(x: 14, y: 7)),
        EmptyTile(position: .init(x: 15, y: 7)),
        
        EmptyTile(position: .init(x: 0, y: 8)),
        EmptyTile(position: .init(x: 1, y: 8)),
        EmptyTile(position: .init(x: 2, y: 8)),
        EmptyTile(position: .init(x: 3, y: 8)),
        EmptyTile(position: .init(x: 4, y: 8)),
        EmptyTile(position: .init(x: 5, y: 8)),
        EmptyTile(position: .init(x: 6, y: 8)),
        Wall(position: .init(x: 7, y: 8)),
        Wall(position: .init(x: 8, y: 8)),
        EmptyTile(position: .init(x: 9, y: 8)),
        EmptyTile(position: .init(x: 10, y: 8)),
        EmptyTile(position: .init(x: 11, y: 8)),
        EmptyTile(position: .init(x: 12, y: 8)),
        EmptyTile(position: .init(x: 13, y: 8)),
        EmptyTile(position: .init(x: 14, y: 8)),
        EmptyTile(position: .init(x: 15, y: 8)),
        
        EmptyTile(position: .init(x: 0, y: 9)),
        EmptyTile(position: .init(x: 1, y: 9)),
        EmptyTile(position: .init(x: 2, y: 9)),
        EmptyTile(position: .init(x: 3, y: 9)),
        EmptyTile(position: .init(x: 4, y: 9)),
        EmptyTile(position: .init(x: 5, y: 9)),
        EmptyTile(position: .init(x: 6, y: 9)),
        EmptyTile(position: .init(x: 7, y: 9)),
        EmptyTile(position: .init(x: 8, y: 9)),
        EmptyTile(position: .init(x: 9, y: 9)),
        EmptyTile(position: .init(x: 10, y: 9)),
        EmptyTile(position: .init(x: 11, y: 9)),
        EmptyTile(position: .init(x: 12, y: 9)),
        EmptyTile(position: .init(x: 13, y: 9)),
        EmptyTile(position: .init(x: 14, y: 9)),
        EmptyTile(position: .init(x: 15, y: 9)),
        
        EmptyTile(position: .init(x: 0, y: 10)),
        EmptyTile(position: .init(x: 1, y: 10)),
        PartialWall(position: .init(x: 2, y: 10), sidesBlock: [.top, .right]),
        EmptyTile(position: .init(x: 3, y: 10)),
        EmptyTile(position: .init(x: 4, y: 10)),
        EmptyTile(position: .init(x: 5, y: 10)),
        EmptyTile(position: .init(x: 6, y: 10)),
        EmptyTile(position: .init(x: 7, y: 10)),
        EmptyTile(position: .init(x: 8, y: 10)),
        EmptyTile(position: .init(x: 9, y: 10)),
        EmptyTile(position: .init(x: 10, y: 10)),
        EmptyTile(position: .init(x: 11, y: 10)),
        EmptyTile(position: .init(x: 12, y: 10)),
        EmptyTile(position: .init(x: 13, y: 10)),
        EmptyTile(position: .init(x: 14, y: 10)),
        EmptyTile(position: .init(x: 15, y: 10)),
        
        PartialWall(position: .init(x: 0, y: 11), sidesBlock: [.bottom]),
        EmptyTile(position: .init(x: 1, y: 11)),
        EmptyTile(position: .init(x: 2, y: 11)),
        EmptyTile(position: .init(x: 3, y: 11)),
        EmptyTile(position: .init(x: 4, y: 11)),
        EmptyTile(position: .init(x: 5, y: 11)),
        PartialWall(position: .init(x: 6, y: 11), sidesBlock: [.top, .left]),
        EmptyTile(position: .init(x: 7, y: 11)),
        EmptyTile(position: .init(x: 8, y: 11)),
        PartialWall(position: .init(x: 9, y: 11), sidesBlock: [.top, .left]),
        PartialWall(position: .init(x: 10, y: 11), sidesBlock: [.bottom, .right]),
        EmptyTile(position: .init(x: 11, y: 11)),
        EmptyTile(position: .init(x: 12, y: 11)),
        EmptyTile(position: .init(x: 13, y: 11)),
        EmptyTile(position: .init(x: 14, y: 11)),
        EmptyTile(position: .init(x: 15, y: 11)),
        
        EmptyTile(position: .init(x: 0, y: 12)),
        EmptyTile(position: .init(x: 1, y: 12)),
        EmptyTile(position: .init(x: 2, y: 12)),
        EmptyTile(position: .init(x: 3, y: 12)),
        PartialWall(position: .init(x: 4, y: 12), sidesBlock: [.bottom, .left]),
        EmptyTile(position: .init(x: 5, y: 12)),
        EmptyTile(position: .init(x: 6, y: 12)),
        EmptyTile(position: .init(x: 7, y: 12)),
        EmptyTile(position: .init(x: 8, y: 12)),
        EmptyTile(position: .init(x: 9, y: 12)),
        EmptyTile(position: .init(x: 10, y: 12)),
        EmptyTile(position: .init(x: 11, y: 12)),
        EmptyTile(position: .init(x: 12, y: 12)),
        EmptyTile(position: .init(x: 13, y: 12)),
        PartialWall(position: .init(x: 14, y: 12), sidesBlock: [.bottom, .left]),
        EmptyTile(position: .init(x: 15, y: 12)),
        
        EmptyTile(position: .init(x: 0, y: 13)),
        EmptyTile(position: .init(x: 1, y: 13)),
        EmptyTile(position: .init(x: 2, y: 13)),
        EmptyTile(position: .init(x: 3, y: 13)),
        EmptyTile(position: .init(x: 4, y: 13)),
        EmptyTile(position: .init(x: 5, y: 13)),
        PartialWall(position: .init(x: 6, y: 13), sidesBlock: [.bottom, .right]),
        EmptyTile(position: .init(x: 7, y: 13)),
        EmptyTile(position: .init(x: 8, y: 13)),
        EmptyTile(position: .init(x: 9, y: 13)),
        EmptyTile(position: .init(x: 10, y: 13)),
        EmptyTile(position: .init(x: 11, y: 13)),
        EmptyTile(position: .init(x: 12, y: 13)),
        EmptyTile(position: .init(x: 13, y: 13)),
        EmptyTile(position: .init(x: 14, y: 13)),
        PartialWall(position: .init(x: 15, y: 13), sidesBlock: [.bottom]),
        
        EmptyTile(position: .init(x: 0, y: 14)),
        EmptyTile(position: .init(x: 1, y: 14)),
        EmptyTile(position: .init(x: 2, y: 14)),
        EmptyTile(position: .init(x: 3, y: 14)),
        EmptyTile(position: .init(x: 4, y: 14)),
        EmptyTile(position: .init(x: 5, y: 14)),
        EmptyTile(position: .init(x: 6, y: 14)),
        EmptyTile(position: .init(x: 7, y: 14)),
        EmptyTile(position: .init(x: 8, y: 14)),
        PartialWall(position: .init(x: 9, y: 14), sidesBlock: [.top, .right]),
        EmptyTile(position: .init(x: 10, y: 14)),
        EmptyTile(position: .init(x: 11, y: 14)),
        EmptyTile(position: .init(x: 12, y: 14)),
        EmptyTile(position: .init(x: 13, y: 14)),
        EmptyTile(position: .init(x: 14, y: 14)),
        EmptyTile(position: .init(x: 15, y: 14)),
        
        EmptyTile(position: .init(x: 0, y: 15)),
        EmptyTile(position: .init(x: 1, y: 15)),
        EmptyTile(position: .init(x: 2, y: 15)),
        EmptyTile(position: .init(x: 3, y: 15)),
        EmptyTile(position: .init(x: 4, y: 15)),
        PartialWall(position: .init(x: 5, y: 15), sidesBlock: [.right]),
        EmptyTile(position: .init(x: 6, y: 15)),
        EmptyTile(position: .init(x: 7, y: 15)),
        EmptyTile(position: .init(x: 8, y: 15)),
        EmptyTile(position: .init(x: 9, y: 15)),
        EmptyTile(position: .init(x: 10, y: 15)),
        EmptyTile(position: .init(x: 11, y: 15)),
        EmptyTile(position: .init(x: 12, y: 15)),
        PartialWall(position: .init(x: 13, y: 15), sidesBlock: [.left]),
        EmptyTile(position: .init(x: 14, y: 15)),
        EmptyTile(position: .init(x: 15, y: 15)),
    ]
}
